// SPDX-License-Identifier: BSD-3-Clause
#include <string.h>
#include "asbridge/decode.h"
#include "asbridge/interpreter.h"
static uint64_t maskw(unsigned w){return w==32?UINT64_C(0xffffffff):UINT64_MAX;}static uint64_t rz(const ASCPU*c,unsigned r,unsigned w){return (r==31u?0:c->x[r])&maskw(w);}static void wz(ASCPU*c,unsigned r,uint64_t v,unsigned w){if(r!=31u)c->x[r]=v&maskw(w);}static uint64_t rs(const ASCPU*c,unsigned r,unsigned w){return (r==31u?c->sp:c->x[r])&maskw(w);}static void ws(ASCPU*c,unsigned r,uint64_t v,unsigned w){v&=maskw(w);if(r==31u)c->sp=v;else c->x[r]=v;}
static void subflags(ASCPU*c,uint64_t a,uint64_t b,uint64_t r,unsigned w){uint64_t m=maskw(w),sign=UINT64_C(1)<<(w-1);a&=m;b&=m;r&=m;uint32_t n=(r&sign)!=0,z=r==0,cc=a>=b,v=((a^b)&(a^r)&sign)!=0;c->nzcv=(n<<31)|(z<<30)|(cc<<29)|(v<<28);}
static int cond(const ASCPU*c,unsigned q){unsigned n=(c->nzcv>>31)&1,z=(c->nzcv>>30)&1,cc=(c->nzcv>>29)&1,v=(c->nzcv>>28)&1;switch(q){case 0:return z;case 1:return!z;case 2:return cc;case 3:return!cc;case 10:return n==v;case 11:return n!=v;case 12:return!z&&(n==v);case 13:return z||(n!=v);case 14:return 1;default:return 0;}}
int as_step(ASCPU*c,ASMemory*m,uint32_t i){ASIR q;if(!as_decode_ir(i,&q))return-1;uint64_t n=c->pc+4,v=0,v2=0,a,r,base,ea;switch(q.op){
case ASIR_NOP:break;case ASIR_HALT:c->halted=true;c->halt_imm=(uint16_t)q.imm;break;case ASIR_MOV_IMM:wz(c,q.rd,q.imm<<q.shift,q.width);break;case ASIR_MOV_KEEP:{uint64_t mk=UINT64_C(0xffff)<<q.shift;wz(c,q.rd,(rz(c,q.rd,q.width)&~mk)|((q.imm<<q.shift)&mk),q.width);break;}
case ASIR_ADD_IMM:ws(c,q.rd,rs(c,q.rn,q.width)+q.imm,q.width);break;case ASIR_SUB_IMM:ws(c,q.rd,rs(c,q.rn,q.width)-q.imm,q.width);break;case ASIR_SUBS_IMM:a=rz(c,q.rn,q.width);r=(a-q.imm)&maskw(q.width);subflags(c,a,q.imm,r,q.width);wz(c,q.rd,r,q.width);break;
case ASIR_ADD_REG:wz(c,q.rd,rz(c,q.rn,q.width)+(rz(c,q.rm,q.width)<<q.shift),q.width);break;case ASIR_SUB_REG:wz(c,q.rd,rz(c,q.rn,q.width)-(rz(c,q.rm,q.width)<<q.shift),q.width);break;
case ASIR_AND_REG:wz(c,q.rd,rz(c,q.rn,q.width)&(rz(c,q.rm,q.width)<<q.shift),q.width);break;case ASIR_ORR_REG:wz(c,q.rd,rz(c,q.rn,q.width)|(rz(c,q.rm,q.width)<<q.shift),q.width);break;case ASIR_EOR_REG:wz(c,q.rd,rz(c,q.rn,q.width)^(rz(c,q.rm,q.width)<<q.shift),q.width);break;case ASIR_MUL:wz(c,q.rd,rz(c,q.rn,q.width)*rz(c,q.rm,q.width),q.width);break;
case ASIR_LOAD:base=rs(c,q.rn,64);ea=q.addr_mode==AS_ADDR_PRE?base+q.offset:base+q.imm;if(q.width==32){uint32_t t;if(as_mem_read32(m,ea,&t))return-2;v=t;}else if(as_mem_read64(m,ea,&v))return-2;wz(c,q.rd,v,q.width);if(q.addr_mode!=AS_ADDR_OFFSET)ws(c,q.rn,base+q.offset,64);break;
case ASIR_STORE:base=rs(c,q.rn,64);ea=q.addr_mode==AS_ADDR_PRE?base+q.offset:base+q.imm;v=rz(c,q.rd,q.width);if(q.width==32){if(as_mem_write32(m,ea,(uint32_t)v))return-2;}else if(as_mem_write64(m,ea,v))return-2;if(q.addr_mode!=AS_ADDR_OFFSET)ws(c,q.rn,base+q.offset,64);break;
case ASIR_LOAD_PAIR64:base=rs(c,q.rn,64);ea=q.addr_mode==AS_ADDR_PRE?base+q.offset:base;if(as_mem_read64(m,ea,&v)||as_mem_read64(m,ea+8,&v2))return-2;wz(c,q.rd,v,64);wz(c,q.rt2,v2,64);if(q.addr_mode!=AS_ADDR_OFFSET)ws(c,q.rn,base+q.offset,64);break;
case ASIR_STORE_PAIR64:base=rs(c,q.rn,64);ea=q.addr_mode==AS_ADDR_PRE?base+q.offset:base;if(as_mem_write64(m,ea,rz(c,q.rd,64))||as_mem_write64(m,ea+8,rz(c,q.rt2,64)))return-2;if(q.addr_mode!=AS_ADDR_OFFSET)ws(c,q.rn,base+q.offset,64);break;
case ASIR_BRANCH:if(q.rd==30u)c->x[30]=n;n=c->pc+q.offset;break;case ASIR_BRANCH_ZERO:if((rz(c,q.rn,q.width)==0)!=(q.imm!=0))n=c->pc+q.offset;break;case ASIR_BRANCH_REG:n=rz(c,q.rn,64);break;case ASIR_BRANCH_COND:if(cond(c,q.cond))n=c->pc+q.offset;break;case ASIR_ADR:wz(c,q.rd,c->pc+q.offset,64);break;case ASIR_ADRP:wz(c,q.rd,(c->pc&~UINT64_C(0xfff))+q.offset,64);break;default:return-1;}c->pc=n;return 0;}
int as_run(ASCPU*c,ASMemory*m,uint64_t lim){while(!c->halted&&lim--){if(c->pc<m->base||c->pc-m->base+4>m->size)return-2;uint32_t i;memcpy(&i,m->data+(size_t)(c->pc-m->base),4);int r=as_step(c,m,i);if(r)return r;}return c->halted?0:1;}
